In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
print('\n\nFonte: Comexstat(http://comexstat.mdic.gov.br/pt/geral), portal para acesso gratuito às estatísticas de\n\
comércio exterior do Brasil, com os dados utilizados para construção da balança comercial brasileira, detalhados\n\
por NCM ou por Municípios do exportador/importador.\n\n')



Fonte: Comexstat(http://comexstat.mdic.gov.br/pt/geral), portal para acesso gratuito às estatísticas de
comércio exterior do Brasil, com os dados utilizados para construção da balança comercial brasileira, detalhados
por NCM ou por Municípios do exportador/importador.




In [2]:
ncm_sh=pd.read_csv('~/git/BD/Comexstat/tab_complementares/NCM_SH.csv',encoding='Latin-1',sep=';')
ncm_sh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6609 entries, 0 to 6608
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   CO_SH6         6609 non-null   int64 
 1   NO_SH6_POR     6609 non-null   object
 2   NO_SH6_ESP     6609 non-null   object
 3   NO_SH6_ING     6609 non-null   object
 4   CO_SH4         6609 non-null   int64 
 5   NO_SH4_POR     6609 non-null   object
 6   NO_SH4_ESP     6609 non-null   object
 7   NO_SH4_ING     6609 non-null   object
 8   CO_SH2         6609 non-null   int64 
 9   NO_SH2_POR     6609 non-null   object
 10  NO_SH2_ESP     6609 non-null   object
 11  NO_SH2_ING     6609 non-null   object
 12  CO_NCM_SECROM  6609 non-null   object
 13  NO_SEC_POR     6609 non-null   object
 14  NO_SEC_ESP     6609 non-null   object
 15  NO_SEC_ING     6609 non-null   object
dtypes: int64(3), object(13)
memory usage: 826.3+ KB


1-Reconhecer os códigos mais abrangentes dos produtos de interesse no sistema internacional SH:

In [3]:
co_sh2_fert=ncm_sh[ncm_sh.NO_SH2_POR.str.lower().str.contains('fertilizante')]['CO_SH2'].unique()
co_sh2_fert

array([31])

Identifica os códigos menos (SH6) abrangentes contidos no código SH2 de fertilizantes:

In [4]:
ncm_sh_list=ncm_sh[ncm_sh.CO_SH2.isin(co_sh2_fert)]['CO_SH6'].unique()
ncm_sh_list

array([310100, 310210, 310221, 310229, 310230, 310240, 310250, 310260,
       310270, 310280, 310290, 310310, 310311, 310319, 310320, 310390,
       310410, 310420, 310430, 310490, 310510, 310520, 310530, 310540,
       310551, 310559, 310560, 310590])

Lê tabela com código comum ao Mercosul, que é o de maior especificação de produto.

In [5]:
ncm=pd.read_csv('~/git/BD/Comexstat/tab_complementares/NCM.csv',encoding='Latin-1',sep=';')
ncm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13654 entries, 0 to 13653
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   CO_NCM          13654 non-null  int64  
 1   CO_UNID         13654 non-null  int64  
 2   CO_SH6          13654 non-null  int64  
 3   CO_PPE          13361 non-null  float64
 4   CO_PPI          13361 non-null  float64
 5   CO_FAT_AGREG    13634 non-null  float64
 6   CO_CUCI_ITEM    13654 non-null  object 
 7   CO_CGCE_N3      13654 non-null  int64  
 8   CO_SIIT         13361 non-null  float64
 9   CO_ISIC_CLASSE  13654 non-null  int64  
 10  CO_EXP_SUBSET   13360 non-null  float64
 11  NO_NCM_POR      13654 non-null  object 
 12  NO_NCM_ESP      13654 non-null  object 
 13  NO_NCM_ING      13654 non-null  object 
dtypes: float64(5), int64(5), object(4)
memory usage: 1.5+ MB


Na última tabela de NCM, localizamos os códigos NCM que se relacionam aos SH6 de fertilizantes.

In [6]:
list_ncm_fert=ncm[ncm.CO_SH6.isin(ncm_sh_list)].CO_NCM.unique()
list_ncm_fert

array([31053000, 31031100, 31031900, 31059011, 31059019, 31059090,
       31031020, 31031030, 31032000, 31039011, 31053010, 31053090,
       31054000, 31055100, 31055900, 31056000, 31010000, 31021010,
       31021090, 31022100, 31022910, 31022990, 31023000, 31024000,
       31025011, 31025019, 31025090, 31026000, 31027000, 31028000,
       31029000, 31031010, 31039019, 31039090, 31041000, 31042010,
       31042090, 31043010, 31043090, 31049010, 31049090, 31051000,
       31052000])

In [7]:
import zipfile

# Caminho para o arquivo ZIP
caminho_arquivo_zip = 'IMP_COMPLETA.zip'

# Abre o arquivo ZIP em modo leitura
with zipfile.ZipFile(caminho_arquivo_zip, 'r') as zip_ref:
    # Lista o conteúdo do arquivo ZIP
    for info in zip_ref.infolist():
        print(info.filename)


IMP_COMPLETA.csv


In [8]:
import zipfile
import pandas as pd
import os

# Caminho para o arquivo ZIP
caminho_arquivo_zip = '~/git/BD/Comexstat/IMP_COMPLETA/IMP_COMPLETA.zip'

# Expandir o caminho com ~ para o diretório raiz do usuário
caminho_completo = os.path.expanduser(caminho_arquivo_zip)

# Número de linhas a serem lidas
num_linhas = 5  # Defina o número de linhas que deseja exibir

# Abrir o arquivo ZIP em modo leitura
with zipfile.ZipFile(caminho_completo, 'r') as zip_ref:
    # Extrair o arquivo CSV temporariamente
    with zip_ref.open('IMP_COMPLETA.csv') as csv_file:
        # Ler as primeiras linhas do arquivo CSV
        df = pd.read_csv(csv_file, nrows=num_linhas, encoding='Latin-1',sep=';')
        # Exibir as primeiras linhas em formato de tabela
        display(df)


CO_ANO  CO_MES    CO_NCM  CO_UNID  CO_PAIS SG_UF_NCM  CO_VIA   CO_URF  \
0    1997       9  29251990       10       87        SP       1   817800   
1    1997       8  85049010       10      399        SP       4   817600   
2    1997       8  54023300       10       63        SP       7  1010900   
3    1997       3  38121000       10      249        SP       1   817800   
4    1997      10  73209000       10      399        SP       4   817600   

   QT_ESTAT  KG_LIQUIDO  VL_FOB  VL_FRETE  VL_SEGURO  
0       200         200    4888       180         24  
1      4891          84   30116       409         93  
2    143834      143834  402427     10121        266  
3      9434        9172   61190      3011        163  
4    222510          49    3638       456         18

In [9]:
import zipfile
import pandas as pd

# Caminho para o arquivo ZIP
caminho_arquivo_zip = 'IMP_COMPLETA.zip'

# Função para filtrar as linhas do DataFrame com base na coluna 'CO_NCM'
def filtrar_chunk(chunk):
    return chunk[chunk['CO_NCM'].isin(list_ncm_fert)]

# Tamanho do chunk
chunk_size = 10000  # Defina o tamanho do chunk conforme necessário

imp_fert=pd.DataFrame()

# Abrir o arquivo ZIP em modo leitura
with zipfile.ZipFile(caminho_arquivo_zip, 'r') as zip_ref:
    # Extrair o arquivo CSV temporariamente
    with zip_ref.open('IMP_COMPLETA.csv') as csv_file:
        # Ler o arquivo CSV em chunks
        chunks = pd.read_csv(csv_file, chunksize=chunk_size, encoding='Latin-1', sep=';')
        
        # Iterar sobre os chunks
        for chunk in chunks:
            # Filtrar o chunk
            chunk_filtrado = filtrar_chunk(chunk)
            
            # Exibir o chunk filtrado (ou realizar outra ação, como processamento adicional)
            imp_fert=pd.concat([imp_fert,chunk_filtrado])


display(imp_fert)

CO_ANO  CO_MES    CO_NCM  CO_UNID  CO_PAIS SG_UF_NCM  CO_VIA  \
266         1997      12  31042090       10       23        RS       1   
874         1997       3  31027000       10      249        SP       1   
1095        1997      11  31042090       10      249        SP       4   
1543        1997      12  31021010       10      831        SC       1   
2273        1997       3  31022100       10       23        RJ       1   
...          ...     ...       ...      ...      ...       ...     ...   
40528384    2024       1  31022100       10      160        SC       1   
40528504    2024       1  31054000       10      160        PR       1   
40528525    2024       1  31051000       10      160        SP       1   
40529356    2024       1  31059090       10       23        SP       1   
40529430    2024       1  31059090       10      245        RS       7   

           CO_URF  QT_ESTAT  KG_LIQUIDO  VL_FOB  VL_FRETE  VL_SEGURO  
266       1015400   7130535     7130535  922261     85567       1935  
874        817800        12           6     103         4          0  
1095       817600        12           1    1197        35          6  
1543       920151   4507463     4507463  549976     54024          0  
2273       717600       144        7200   15582       681          0  
...           ...       ...         ...     ...       ...        ...  
40528384   917800   1000000     1000000  148730     17530         52  
40528504   917800    235200      235200  177990     21624        121  
40528525   817800     13500       13500   60365      1297          0  
40529356   917800     15750       15750   39511       627        324  
40529430  1010252     12750       12750   63486      5135          0  

[100430 rows x 13 columns]

In [13]:
import os
os.getcwd()

'/home/andre301267/git/BD/Comexstat/IMP_COMPLETA'

In [14]:
imp_fert.to_csv('~/git/BD/temp/imp_fert1.csv', index=False)